version: '3.1'

services:
    web:
        build: docker/python
        command: >
            sh bin/start.sh
        volumes:
            - .:/code
        ports:
            - "8000:8000"
        depends_on:
            - db
    db:
        image: postgres:10
        environment:
            POSTGRES_DB: "postgres"
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "postgres"
        ports:
            - "5432:5432"
        volumes:
            - ~/docker/postgres:/var/lib/postgresql/data

volumes:
    dbdata:
